---
title: "PO_1005"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(readr)
library(leaflet)
```

```{r}
df_final <- read.csv("https://raw.githubusercontent.com/Magnusjahren/Datapo/main/Data_po_1005.csv", sep = " ")

df_final$DATE <- as.Date(df_final$DATE)
```

```{r}


df_final %>%
  filter(STORE == 12) %>%
  group_by(BRAND) %>% 
ggplot(aes(x = DATE, y = SUM_PROFIT, color = BRAND)) +
  geom_line() +
  labs(title = "Weekly profit of beer in Chicago by brand",
       subtitle = "1992",
       x = "Date",
       y = "Sales",
       color = "Brand") +
  theme_bw() +
  theme(legend.position = "bottom",
        legend.title = element_blank(),
        axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
df_final1 <- df_final %>%
filter(STORE == 12) %>%
group_by(BRAND) %>%
summarise(MOVE_SUM = sum(MOVE_SUM))

pie1 <-ggplot(df_final,aes(x="", y=MOVE_SUM, fill=BRAND)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) +
  theme_void() +
  labs(title = "Markedshare beer brands in %", fill = "Brand")
```

```{r}
df_final2 <- df_final %>% 
  filter(STORE == 12) %>%
  rename(unemployed = unemp) %>% 
  rename(education = educ) %>% 
  rename(workingwoman = workwom) %>% 
  select(single, retired, unemployed, education, poverty, workingwoman) %>% 
  pivot_longer(cols = c("single", "retired", "unemployed", "education", "poverty", "workingwoman"), names_to = "name", values_to = "val")


pie2 <- ggplot(df_final2,aes(x="", y=val, fill=name)) +
  geom_bar(width = 1, stat = "identity") +
  coord_polar("y", start=0) +
  theme_void() +
  labs(title = "Customer share of beer sales in Chicago", fill = "Group")

```

```{r}
gridExtra::grid.arrange(pie1,pie2, ncol=2)
```

```{r}
df_final %>% 
  filter(STORE == 12) %>% 
  group_by(WEEK) %>% 
  ggplot(aes(x=DATE, y= beer_sum)) +
  geom_line() +
  theme_bw() +
  labs(title = "All beer sales in all stores", x = "Time", y = "Sales")
```
